INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (4, 'Fervex', 'Granule suspensie: un plic conține paracetamol 500 mg + maleat de feniramină 25 mg + vit. C 200 mg; ct. x 8 plicuri x 13,1 g granule', 70, 19, 16, 4, 4, 5);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (5, 'Crema acneica cu sulf & extracte natural', 'CREMA ANTIACNEICA CU SULF, EXTRACTE NATURALE DE PROPOLIS SI CEAI VERDE, ACID SALICILIC, VITAMINA E PENTRU TENURI SENSIBILE SI/SAU IRITATE', 12, 43, 43, 4, 5, 9);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (3, 'Arnigel', 'ARNIGEL® este un medicament homeopatic utilizat în mod tradițional în tratamentul local al traumatologiei benigne în absența plăgilor (echimoze', 24, 67, 52, 4, 3, 10);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (6, 'Alfa Infinit Potenta comprimate', 'Alfa Infinit Potenta comprimate de la Dacia Plant este solutia 100% naturala', 7, 135, 120, 5, 6, 8);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (7, 'Alfa Mai Fertil comprimate', 'Alfa Mai Fertil comprimate de la Dacia Plant este solutia 100% naturala', 5, 50, 45, 5, 7, 8);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (8, 'Mami și Bebe Biosept', 'Sirop conceput pentru sugari. Combinație naturală de plante cu efect sigur, dar cu acțiune blândă, pentru sugari. Conține lichen de piatră,  frunze de măslin, turmeric și trifoiște de baltă. Ingrediente naturale asimilate cu ușurință de către organism. Este îndulcit cu fructoză extrasă din fructe. Fără îndulcitori artificiali.', 40, 35, 30, 4, 8, 7);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (9, 'Nurofen Express Forte 400mg, 20 capsule', 'Pastile pentru dureri de cap', 6, 30, 30, 4, 4, 3);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (10, 'Plasturi impermeabili, 10x6cm, 5bucati, Urgo', 'Plasturi impermeabili', 10, 25, 25, 4, 9, 4);
INSERT INTO public.products (id, name, description, stock, default_price, actual_price, rating, category_id, supplier_id) VALUES (11, 'Voltarol', 'Gel pentru dureri musculare', 8, 45, 35, 5, 3, 6);
